###
GET http://localhost:3000/bank-accounts

###
GET http://localhost:3000/bank-accounts/1635280c-515f-46c7-ae0e-e347ed59924a

###
POST  http://localhost:3000/bank-accounts
Content-Type: application/json

{
  "account_number": "2222-22"
}

###
POST http://localhost:3000/bank-accounts/transfer
Content-Type: application/json

{
  "from": "1111-11",
  "to": "5555-55",
  "amount": 50
}

